### PR TITLE
Future Proofing

### PR DESCRIPTION
**Pull request by KendrickLamar2003**
As part of my job to future-proof the documentation of QC for the next update, I have decided to do the same for the discord bot. There is now a `renderer` command which tells the user about Vulkan, GL4ES, and Zink (which are coming next update). There is also a `list` command, which directs the user to a Spreadsheet and Form, with the former being a list of supported mods and a form where the user can submit a working mod in QC, which will be automatically added to the list. Props to the Judge for helping me with the Info for the`renderer`command, and with the README (of QC) in general.

### CODE REVIEW

**Comment by TecEash1** [comment]
I’m guessing u didn’t test any of this…

**Comment by swaggio7** [comment]
Unfortunately, yes. I forgot to mention THIS STUPID CANT FIND MODULE ERROR KEEPS ON APPEARING

**Comment by swaggio7** [comment]
Even, I also get this SyntaxError: missing ) after argument list error.

**Comment by TecEash1** [comment]
## Problems 

- There are *way to many* errors in the code at the moment, it will definitely not run as intended

- The mod list thing in ``/lists`` (which has an error) is not allowed by the mods, I told u this before btw so it definitely wouldn't be put into the bot

- You deleted all of the embeds and added them back for some reason, this may cause problems when I go over to check them all and I will probably just have to end up re-replacing them, but probably using a tool to check the differences

- So far the Renderer Embed title and description (also command one) is the only thing that seems ok, trying to execute either of these things would have 2/3 errors I assume

**Comment by TecEash1** [comment]
Just a quick update: 

The performance command was added: https://github.com/Cartrigger/QCXRSoonBot/commit/f0d5cce00a9c3b9b3b6cec15b1a446f8a6edc664

The renderer command will be added soon with relevant parameters/presets

**Pull request closed without merging**
