### PR TITLE
QoL fixes

### PR DESCRIPTION
**Pull request by Novampr**
sorry for the messy comits :(

my git just HATES me for some random reason, basically just look at last comit, the rest is just something from last time

### CODE REVIEW

**Comment by TecEash1** [comment]
So which commits are ur new ones?

**Comment by DevLimeAtSkyo** [comment]
Last 2/3

**Comment by DevLimeAtSkyo** [comment]
And this one :)
Contributers

**Comment by TecEash1** [comment]
not that commit…. wasn’t talkin about doin it like that 💀. Also if someone new contributes that wont be updated…

**Comment by DevLimeAtSkyo** [comment]
Image?

**Comment by DevLimeAtSkyo** [comment]
gone

**Pull request closed without merging**
