### PR TITLE
Fix some grammar and self-hosted guide :3

### PR DESCRIPTION
**Pull request by Novampr**
Also changed the embed that appears when you run mentionsupportchannels in a support channel

Not sure what happened:

Anyways I added a new guide for self-hosted servers as there wasn't really anything in the bot to fill this so I added a new button to servers command which shows the self-hosted server guide.

Also if you ever plan on making a complex embed please use [this](https://embed.dan.onl/) and who ever made it is my saviour

### CODE REVIEW

**Comment by DevLimeAtSkyo** [comment]
Fixed some conflicts 👍🏼

**Comment by DevLimeAtSkyo** [comment]
Next pull request idea:
Format all the files 😭

**Comment by Cartrigger** [comment]
fixed a merge conflict

**Comment by Cartrigger** [comment]
didn't mean to merge but /shrug

**Comment by DevLimeAtSkyo** [comment]
Cool 👍

**Comment by DevLimeAtSkyo** [comment]
Fixed some more conflicts

**Comment by Cartrigger** [comment]
i can pull it if you want

**Comment by DevLimeAtSkyo** [comment]
Works for me, allows me to push my own commits again without messing up this pr

**Comment by TecEash1** [comment]
I’m sorry for all of these things 💀

**Comment by DevLimeAtSkyo** [comment]
wdym?

**Comment by TecEash1** [comment]
*The stuff above which says pending…*

**Comment by DevLimeAtSkyo** [comment]
Just wondering what happened here, pr pulled but the bot doesn't have the extra button?

**Pull request merged**
